# Generated by Django 4.1.5 on 2023-01-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_migracion_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importancia',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
